"""add document metadata and chunk index

Revision ID: 556e0a4278b7
Revises: d90f1389723e
Create Date: 2026-08-12 18:54:09.919240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector  # needed for the vector column type; autogenerate doesn't add this on its own
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '556e0a4278b7'
down_revision: Union[str, Sequence[str], None] = 'd90f1389723e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('chunk_index', sa.Integer(), nullable=False))
    op.alter_column('chunks', 'content',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.add_column('documents', sa.Column('mime_type', sa.String(), nullable=False))
    op.add_column('documents', sa.Column('document_type', sa.String(), nullable=False))
    op.add_column('documents', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.alter_column('documents', 'filename',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('messages', 'content',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'content',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('documents', 'filename',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('documents', 'metadata')
    op.drop_column('documents', 'document_type')
    op.drop_column('documents', 'mime_type')
    op.alter_column('chunks', 'content',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('chunks', 'chunk_index')
    # ### end Alembic commands ###
